#!/usr/bin/env bash
#Nginx must be running, and listening on port 80 in 5 lines
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
